name: Branch Sync

on:
  push:
    # This will trigger the workflow for pushes to any branch
    branches:
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0 # Necessary to fetch all history for branches

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Sync branches
        run: |
          # Fetch all branches
          git fetch --all
          
          # List of branches to be synced, space-separated
          BRANCHES="main feature/read-resp feature/write-resp"
          
          # The branch to sync from, in this case, it's the branch that triggered the workflow
          SOURCE_BRANCH="${GITHUB_REF#refs/heads/}"
          
          # Loop over each branch and merge changes
          for BRANCH in $BRANCHES; do
            # Skip if SOURCE_BRANCH and BRANCH are the same
            if [[ "$BRANCH" == "$SOURCE_BRANCH" ]]; then
              continue
            fi

            git checkout $BRANCH
            git merge $SOURCE_BRANCH --ff-only || (echo "Conflict merging $SOURCE_BRANCH into $BRANCH" && exit 1)
            git push origin $BRANCH
          done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
